#!/bin/bash
#number of threads:
for  t  in  1 2 4 6 8
do
    # echo NUMT = $t
    # number of subdivisions:
    for s in  5 10 50 100 500 1000 5000 
    do
        # echo NUMS = $s
        g++   -DNUMNODES=$s   -DNUMT=$t   two.cpp  -o two -lm  -fopenmp
        ./two
    done
done
